name: sidequest_mark_ii
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  carousel_slider: ^4.2.1
  flutter_screenutil: ^5.9.3
  flutter_svg: ^2.0.10+1
  supabase_flutter: ^2.5.11
  custom_sliding_segmented_control: ^1.8.3
  shared_preferences: ^2.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - Assets/Images/purp.png
    - Assets/Images/lad.png
    - Assets/Images/tr.png
    - Assets/Images/pr.png
    - Assets/Images/me.jpg

    - Assets/Icons/bell.svg
    - Assets/Icons/google.svg
    - Assets/Icons/arrow.svg
    - Assets/Icons/gear.svg
    - Assets/Icons/bell2.svg
    - Assets/Icons/doc.svg
    - Assets/Icons/down.svg
    - Assets/Icons/share.svg
    - Assets/Icons/dl.svg
    - Assets/Icons/ios.svg


  fonts:
    - family: play
      fonts:
        - asset: fonts/main.ttf
